# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_make_gaussian <- function(link) {
    .Call(`_xglm_rcpp_make_gaussian`, link)
}

rcpp_make_binomial <- function(link) {
    .Call(`_xglm_rcpp_make_binomial`, link)
}

rcpp_make_poisson <- function(link) {
    .Call(`_xglm_rcpp_make_poisson`, link)
}

rcpp_make_gamma <- function(link) {
    .Call(`_xglm_rcpp_make_gamma`, link)
}

rcpp_glm_fit <- function(x, y, sample_weights, offset, family, maxit, tol) {
    .Call(`_xglm_rcpp_glm_fit`, x, y, sample_weights, offset, family, maxit, tol)
}

